[tool.poetry]
name = "timesfm"
version = "2.0.0"
description = "A time series foundation model."
authors = [
    "Rajat Sen <senrajat@google.com>",
    "Yichen Zhou <yichenzhou@google.com>",
    "Abhimanyu Das <abhidas@google.com>",
    "Petros Mol <pmol@google.com>",
    "Michael Chertushkin <chertushkinmichael@gmail.com>"
]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "timesfm", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
numpy = ">=1.26.4"
huggingface_hub = { version = ">=0.23.0", extras = ["cli"] }
safetensors = ">=0.5.3"
torch = { version = ">=2.0.0", extras = ["cuda"], optional = true }
flax = { version = ">=0.8.2", optional = true }
jax = { version = ">=0.4.26", optional = true }
optax = { version = ">=0.2.2", optional = true }

[tool.poetry.extras]
torch = ["torch"]
flax = ["flax", "jax", "optax", "einshape", "orbax-checkpoint", "jaxtyping", "typeguard"]

[tool.ruff]
line-length = 88
indent-width = 2


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

