# This project can be installed with `python3 -m pip install -e .` from the main directory. 

[project]
name = "timesfm-jax"
packages = [
    { include = "*", from = "src" },
]
version = "0.0.1"
description = "Open weights time-series foundation model from Google Research."
version = "1.0.1"
dependencies = [
    "jax==0.4.26",
    "paxml==1.4.0",
    "praxis==1.4.0",
    "jaxlib==0.4.26",
    "numpy==1.26.4",
    "pandas==2.1.4",
    "einshape==1.0.0",
    "utilsforecast==0.1.10",
    "huggingface_hub[cli]==0.23.0", 
    "scikit-learn==1.5.1",
]
authors = [
    "Rajat Sen <senrajat@google.com>",
    "Yichen Zhou <yichenzhou@google.com>",
    "Abhimanyu Das <abhidas@google.com>",
    "Petros Mol <pmol@google.com>",
    "Justin Güse <guese.justin@gmail.com>",
]
readme = "README.md"
keywords = ["time series", "timesfm", "forecast", "time series model"]
homepage = "https://github.com/google-research/timesfm"
repository = "https://github.com/google-research/timesfm"
classifiers = [
    "Environment :: Console",
    "Framework :: Flake8",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
einshape = ">=1.0.0"
numpy = ">=1.26.4"
pandas = ">=2.1.4"
paxml = "1.4.0"
jax = "0.4.26"
jaxlib = "0.4.26"
utilsforecast = "^0.1.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
